In [1]:
import torch
from COTR.models.pl_cotr import Baseline

In [3]:
debug = torch.load('debug.pth')

In [4]:
batch = debug['batch']
pred = debug['predict']

In [5]:
batch.keys()

dict_keys(['base_img', 'aug_imgs', 'target_corrs', 'target_mask', 'base_img_idx', 'aug_img_idx'])

In [6]:
pred.keys()

dict_keys(['pred_corr_volum', 'ref_emb', 'aug_emb', 'corr_loss'])

In [7]:
pred['pred_corr_volum'].shape

torch.Size([72, 16, 16, 16, 16])

In [10]:
pred_corrs = pred['pred_corr_volum']
pred_corrs[0].view([16*16, -1]).max(dim=-1).values

tensor([0.0278, 0.0318, 0.0196, 0.0000, 0.0553, 0.0603, 0.0000, 0.0500, 0.0486,
        0.0045, 0.0059, 0.0861, 0.0331, 0.0680, 0.0000, 0.0000, 0.0084, 0.0322,
        0.0000, 0.0011, 0.0302, 0.0168, 0.0014, 0.0446, 0.0243, 0.0378, 0.0351,
        0.0440, 0.0000, 0.0284, 0.0000, 0.0000, 0.0000, 0.0050, 0.0000, 0.0354,
        0.0464, 0.0578, 0.0000, 0.0000, 0.0040, 0.0000, 0.0000, 0.0619, 0.0000,
        0.0350, 0.0593, 0.0554, 0.0023, 0.0000, 0.0000, 0.0328, 0.0766, 0.0000,
        0.0689, 0.0442, 0.0048, 0.0481, 0.0000, 0.0106, 0.0235, 0.0000, 0.0261,
        0.0335, 0.0374, 0.0285, 0.0101, 0.0203, 0.0014, 0.0000, 0.0141, 0.0773,
        0.0295, 0.0000, 0.0616, 0.0000, 0.0124, 0.0184, 0.0221, 0.0255, 0.0000,
        0.0334, 0.0478, 0.0498, 0.0199, 0.0246, 0.0263, 0.0534, 0.0200, 0.0396,
        0.0334, 0.0309, 0.0106, 0.0444, 0.0411, 0.0246, 0.0000, 0.0000, 0.0000,
        0.0125, 0.0279, 0.0171, 0.0372, 0.0522, 0.0345, 0.0048, 0.0239, 0.0364,
        0.0348, 0.0000, 0.0424, 0.0117, 

In [2]:
model = Baseline.load_from_checkpoint('checkpoints/baseline/lightning_logs/version_12/checkpoints/epoch=103-step=51999.ckpt')

In [4]:
ckpt = torch.load('checkpoints/baseline/lightning_logs/version_12/checkpoints/epoch=103-step=51999.ckpt')
st = ckpt['state_dict']

In [2]:
model = Baseline(embed_dim=256, num_classes=1000, partial_fc=True)

In [26]:
model.load_state_dict(torch.load('1250-step.pth'))

<All keys matched successfully>

In [27]:
pred = torch.load('1250-emb.pth')

In [5]:
pred.shape

torch.Size([1, 256])

In [28]:
pred

tensor([[-6.2387e-04,  4.4615e-03, -2.8122e-02, -4.1100e-03, -8.3522e-03,
          2.0593e-03,  6.6530e-03,  3.5419e-03,  2.3051e-02,  4.9215e-03,
          1.2610e-02, -4.2305e-03,  1.5671e-02, -6.9876e-03, -6.3740e-03,
         -4.4348e-03,  2.7904e-03,  9.7190e-03, -2.5585e-03, -2.3342e-05,
         -1.4082e-02, -3.6896e-03, -2.5564e-02, -1.7033e-02, -7.8566e-03,
         -7.3100e-03, -3.6839e-03, -6.4455e-03, -1.5738e-02,  1.4755e-02,
          7.3263e-03,  1.5184e-02,  5.7474e-03, -1.4470e-02, -1.7960e-02,
          7.0409e-03, -2.7325e-02,  1.7590e-02, -4.2951e-03, -6.2063e-03,
         -5.3351e-03, -3.6285e-03,  3.0557e-03, -7.5411e-03,  1.6104e-02,
          7.4454e-05, -4.6136e-03,  6.6063e-03,  1.5514e-02,  7.9274e-03,
          1.1412e-02,  1.3632e-03, -3.3163e-03, -8.0841e-03, -9.3262e-03,
          2.6317e-03, -7.9723e-03, -8.8808e-03,  6.1286e-03,  1.5282e-02,
          1.4448e-02, -1.4051e-02, -2.6687e-03,  5.1912e-03, -4.3421e-03,
         -1.0494e-02,  1.9260e-02, -1.

In [30]:
pred_2 = model(torch.ones([1, 3, 256, 256]))

In [35]:
torch.abs(pred_2[1].cpu() - pred.cpu()).max()

tensor(3.7500e-05, grad_fn=<MaxBackward1>)

In [31]:
pred_2[1]

tensor([[-6.2313e-04,  4.4342e-03, -2.8121e-02, -4.1138e-03, -8.3677e-03,
          2.0415e-03,  6.6446e-03,  3.5463e-03,  2.3054e-02,  4.9364e-03,
          1.2605e-02, -4.2331e-03,  1.5668e-02, -6.9865e-03, -6.3663e-03,
         -4.4305e-03,  2.7954e-03,  9.7187e-03, -2.5802e-03, -3.8778e-05,
         -1.4067e-02, -3.6857e-03, -2.5577e-02, -1.7037e-02, -7.8505e-03,
         -7.3387e-03, -3.6796e-03, -6.4506e-03, -1.5744e-02,  1.4750e-02,
          7.3254e-03,  1.5171e-02,  5.7450e-03, -1.4475e-02, -1.7959e-02,
          7.0432e-03, -2.7333e-02,  1.7593e-02, -4.2900e-03, -6.2241e-03,
         -5.3433e-03, -3.6339e-03,  3.0715e-03, -7.5231e-03,  1.6092e-02,
          8.0585e-05, -4.6116e-03,  6.5899e-03,  1.5512e-02,  7.9371e-03,
          1.1411e-02,  1.3556e-03, -3.3051e-03, -8.0950e-03, -9.3317e-03,
          2.6284e-03, -7.9583e-03, -8.8797e-03,  6.1268e-03,  1.5296e-02,
          1.4448e-02, -1.4054e-02, -2.6520e-03,  5.1972e-03, -4.3457e-03,
         -1.0500e-02,  1.9257e-02, -1.

In [36]:
ckpt = torch.load('checkpoints/baseline/lightning_logs/version_18/checkpoints/epoch=9-step=1249.ckpt')['state_dict']

In [37]:
for k, v in model.named_parameters():
    d = torch.abs(ckpt[k].cpu() - v.cpu()).sum()
    print(k, float(d))

debug_tensor_data 0.0
backbone.conv1.weight 0.0
backbone.bn1.weight 0.0
backbone.bn1.bias 0.0
backbone.layer1.0.conv1.weight 0.0
backbone.layer1.0.bn1.weight 0.0
backbone.layer1.0.bn1.bias 0.0
backbone.layer1.0.conv2.weight 0.0
backbone.layer1.0.bn2.weight 0.0
backbone.layer1.0.bn2.bias 0.0
backbone.layer1.0.conv3.weight 0.0
backbone.layer1.0.bn3.weight 0.0
backbone.layer1.0.bn3.bias 0.0
backbone.layer1.0.downsample.0.weight 0.0
backbone.layer1.0.downsample.1.weight 0.0
backbone.layer1.0.downsample.1.bias 0.0
backbone.layer1.1.conv1.weight 0.0
backbone.layer1.1.bn1.weight 0.0
backbone.layer1.1.bn1.bias 0.0
backbone.layer1.1.conv2.weight 0.0
backbone.layer1.1.bn2.weight 0.0
backbone.layer1.1.bn2.bias 0.0
backbone.layer1.1.conv3.weight 0.0
backbone.layer1.1.bn3.weight 0.0
backbone.layer1.1.bn3.bias 0.0
backbone.layer1.2.conv1.weight 0.0
backbone.layer1.2.bn1.weight 0.0
backbone.layer1.2.bn1.bias 0.0
backbone.layer1.2.conv2.weight 0.0
backbone.layer1.2.bn2.weight 0.0
backbone.layer1.2.bn2